### ISSUE TITLE
群晖docker无法启动：ModuleNotFoundError: No module named 'watchdog'

### ISSUE THREAD

**Issue by sinnzz** [sgpublic/nas-tools-enhanced#2]
群晖docker无法启动：ModuleNotFoundError: No module named 'watchdog'

**Comment by sgpublic** [comment]
v2.9.2-x 与 v2.10 及以后的版本不兼容，不能直接更新，请尝试重新拉取镜像。

重新拉取之后还是不行的话请附上完整日志。

**Comment by wx407810105** [comment]
错误代码日志片段：
```
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/local/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
Traceback (most recent call last):
  File "/nas-tools-enhanced/run.py", line 7, in <module>
    from watchdog.events import FileSystemEventHandler
ModuleNotFoundError: No module named 'watchdog'
```

好像是poetry加载有问题，会一直因为 `ModuleNotFoundError: No module named 'watchdog'` 而无法继续下载组件，直接跳转运行 `start.sh` 又因组件未下载而导致容器一直退出。

临时解决办法：通过改 `REPO_URL` 为 `https://gitee.com/sgpublic/nas-tools-enhanced.gitanced.git`，卡 gitee 账密登录原因代码停顿不继续情况下，通过终端连接容器运行 `/nas-tools-enhanced/docker/entrypoint.sh`（提示登录 gitee直接回车就可以跳过继续）完成组件下载，下载完成后禁止自动更新就可以正常运行（重启也没问题）。

注意：通过直接运行 `start.sh` 脚本下载的组件，在下次重启依旧存在问题，我已测试过了。

**Comment by sgpublic** [comment]
我也测出来是 `poetry install` 的问题，但没整明白是为什么

**Comment by wx407810105** [comment]
以PUID=${PUID}，PGID=${PGID}的身份启动start.sh脚本做测试情况
终端/bin/bash测试 ` exec su-exec "${PUID}":"${PGID}" "./start.sh" ` 报错如下
```
Creating virtualenv nas-tools-enhanced-8CGAFfKI-py3.10 in /.cache/pypoetry/virtualenvs
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument dest: the destination . is not write-able at /
Creating virtualenv nas-tools-enhanced-8CGAFfKI-py3.10 in /.cache/pypoetry/virtualenvs
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument dest: the destination . is not write-able at /
```
以设定PUID=0 PGUI=0后`exec su-exec 0:0 "./start.sh" ` ` exec su-exec root "./start.sh` 等都能正常运行。
容器环境变量设置PUID=0 PGUI=0，命令` exec su-exec "${PUID}":"${PGID}" "./start.sh" ` 也报上述错误。
好像是切换身份后访问目录权限有问题。直接/bin/bash终端下执行/nas-tools-enhanced/docker/entrypoint.sh却能够正常运行，又令人费解?!

**Comment by sinnzz** [comment]
大佬们有解决办法么？

**Comment by sgpublic** [comment]
目前推荐退回 `2.9.2-02` 使用，我对项目还不是很熟，v2.10 更新可能会比较消极（或者等其他大佬推 PR xD

**Comment by chengnan049** [comment]
> 目前推荐退回 `2.9.2-02` 使用，我对项目还不是很熟，v2.10 更新可能会比较消极（或者等其他大佬推 PR xD

大佬还打算更新么

**Comment by sgpublic** [comment]
> 大佬还打算更新么

最近忙，过段时间稳定下来了应该会继续
